###
GET localhost:8081/account/2

###
POST http://localhost:8081/account
Content-Type: application/json

{
  "iban": "NL05ABNA6383931601",
  "currency": "NL",
  "balance": "1234.5"
}

###
POST http://localhost:8081/account
Content-Type: application/json

{
  "iban": "PL39109024029221197278987884",
  "currency": "PL",
  "balance": "20000.5"
}

###
POST http://localhost:8081/account
Content-Type: application/json

{
  "iban": "SK9833455779659742266621",
  "currency": "SK",
  "balance": "500"
}

###
POST http://localhost:8081/addCustomer/2/1

###
DELETE http://localhost:8081/deleteCustomer/2/1

###
DELETE localhost:8081/account/1