###
GET localhost:8081/account

###
POST http://localhost:8081/account
Content-Type: application/json

{
  "IBAN": "NL35ABNA6289099205",
  "currency": "NL",
  "balance": "1234.5"
}

###
POST http://localhost:8081/addCustomer/1/2