###
GET localhost:8081/customer

###
POST localhost:8081/customer
Content-Type: application/json

{
  "name": "Samo",
  "surname": "Lang",
  "sex": "MALE",
  "nationality": "SK",
  "cardNumber": "1234",
  "dateOfExpiry":"20.12.2000",
  "dateOfIssue": "1.1.2005",
  "dateOfBirth": "1.1.2000"
}