###
POST http://localhost:8081/transfer
Content-Type: application/json

{
  "date": "2022-03-02",
  "amount": "50",
  "debtorIBAN": "PL39109024029221197278987884",
  "creditorIBAN": "NL05ABNA6383931601",
  "message": "money transfer"
}

###
POST http://localhost:8081/transfer
Content-Type: application/json

{
  "date": "2024-03-02",
  "amount": "250",
  "debtorIBAN": "NL05ABNA6383931601",
  "creditorIBAN": "PL39109024029221197278987884",
  "message": "money transfer"
}

###
POST http://localhost:8081/transfer
Content-Type: application/json

{
  "date": "2024-03-02",
  "amount": "350",
  "debtorIBAN": "NL05ABNA6383931601",
  "creditorIBAN": "PL39109024029221197278987884",
  "message": "Transfer"
}

###
POST http://localhost:8081/transfer
Content-Type: application/json

{
  "date": "2024-03-02",
  "amount": "350",
  "debtorIBAN": "NL05ABNA6383931601",
  "creditorIBAN": "SK9833455779659742266621",
  "message": "Transfer"
}

###
GET http://localhost:8081/transfer/history

###
GET http://localhost:8081/transfer/search/amount/250

###
GET http://localhost:8081/transfer/search/IBAN/NL05ABNA6383931601